### ISSUE TITLE
Continous action space with multi dimension/vector

### ISSUE THREAD

**Issue by ayush488** [instadeepai/catx#22]
Will CATX work when I have action space which is a real/ discrete values vector say of 50 dimensions..
eg: a 50-d vector where each dimension can have 5 possible values... ie total of 5^50 actions.. this could easily be 10^50 also...
Let me know if and how CATX can be used for this?

**Comment by cyprienc** [comment]
Hello @ayush488 - no it won't. CATS was designed to work with a one-dimensional action space.
